{% set name = "napari-sif-reader" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-sif-reader-{{ version }}.tar.gz
  sha256: c1e983ac5c6dca43838e18737c261e4362f7133174c9fa683cbdab49cb053d46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - python >=3.8
    - sif-parser

test:
  imports:
    - napari_sif_reader
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rjlopez2/napari-sif-reader
  summary: This is a simple wraper to read .sif format files from Andor Technology.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - rjlopez2
